
exports.seed = knex =>
  knex('todos').insert([ 
    { id: 1,
      title: 'Item Seven',
      description: 'Food supply',
      completed:'false',
      vendor_fee: '$234',
      event_id: 1,
      vendor_id: 1,
      user_id: 1,
    },
    { id: 2,
      title: 'Hall Decorations',
      description: 'Interior decors',
      completed:'false',
      vendor_fee: '$236',
      event_id: 3,
      vendor_id: 2,
      user_id: 2,
    },
    { id: 3,
      title: 'Water',
      description: 'Water items',
      completed:'false',
      vendor_fee: '$204',
      event_id: 4,
      vendor_id: 3,
      user_id: 3,
    },
    { id: 4,
      title: 'cleaning services',
      description: '09876131321',
      completed:'false',
      vendor_fee: '$834',
      event_id: 5,
      vendor_id: 4,
      user_id: 4,      
    },
    { id: 5,
      title: 'Entertainment',
      description: 'entertainment',
      completed:'false',
      vendor_fee: '$634',
      event_id: 2,
      vendor_id: 5,
      user_id: 5,
    },
  ]);

